version: 0.2

env:
  variables:
    STACK_NAME: examples-nat
    PRIVATE_ROUTE_TABLES: rtb-0eee90cf29e333813,rtb-0c1d060b614e74b88
    PUBLIC_SUBNET: subnet-03ad595bb28ce7679

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - bin/deploy